/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <fun>
#include <codmod>

new nazwa[] = "Buty szturmowego"
new opis[] = "Nie slychac twoich krokow"


public plugin_init() 
{
	register_plugin(nazwa, "1.0", "QTM_Peyote");
	
	cod_register_perk(nazwa, opis);
}

public cod_perk_enabled(id)
	set_user_footsteps(id, 1);
	
public cod_perk_disabled(id)
	set_user_footsteps(id, 0);
	
