/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <codmod>

new const perk_name[] = "Przysposobienie obronne";
new const perk_desc[] = "Dostajesz 20 wytrzymalosci";


public plugin_init() 
{
	register_plugin(perk_name, "1.0", "QTM_Peyote");
	
	cod_register_perk(perk_name, perk_desc);
}
public cod_perk_enabled(id)
	cod_set_user_bonus_stamina(id, cod_get_user_stamina(id, 0, 0)+20);

public cod_perk_disabled(id)
	cod_set_user_bonus_stamina(id, cod_get_user_stamina(id, 0, 0)-20);
